#!/usr/bin/env tclsh

package require http

source [file join [file dirname [info script]] app/install.tcl]

proc version {} {
    return 0.0.1
}

proc main {args} {
    set first_arg [lindex $args 1]

    if {$first_arg != {}} {
        switch $first_arg {
            {install} { ::mug::install::install [lrange $args 2 end] } 
        }
    } else {
        puts "Mug - a Tcl package manager\n"
        puts "Usage: [lindex $args 0] <command>\n"
        puts "Where command is one of:"
        puts "  install\n"
        puts "mug@[version] [info script]"
    }

    #puts [match_version "3.1.4" [parse_version_pattern ">1"]]
    #provide_autoloader [pwd]
    #puts [find_teapot_package "http://teapot.activestate.com/" "base64" "2.4.2"]
}

main $::argv0 {*}$::argv
